alias dotfiles="/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME"
alias dss="dotfiles status --short"
alias ..="cd .."
alias l="ls -a"
alias t="tree -a"
alias c="clear"
alias wk="~/code/webkom"
alias lego="~/code/webkom/lego"
alias webapp="~/code/webkom/lego-webapp"
alias it="~/code/itdagene"
alias subjects="~/code/subjects"
alias yr="curl 'wttr.in/?F&lang=nb'"
alias zshrc="vim ~/.zshrc"
alias vimrc="vim ~/.vimrc"
alias yabairc="vim ~/.config/yabai/yabairc"
alias skhdrc="vim ~/.config/skhd/skhdrc"
alias ds='docker ps --format '\''table {{.ID}}\t{{.Names}}\t{{.Status}}'\'
