"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000
add_newline = true

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$guix_shell\
$buf\
$python\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$time\
$status\
$os\
$container\
$shell\
$character"""

[python]
    format = '[${symbol}${pyenv_prefix}( )(\($virtualenv\) )]($style)'

